baseurl = "/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-uk"
title = "Blog - Endy WindAflame"
theme = "hugo-initio"

[params]
    favicon = ""
# Shared
#    customsharethis = ""
    name = "Endy WindAflame"
    DateForm = "January 2, 2006"
    email = "dev.windaflame@gmail.com"

# Headers
    avatar = "guy.jpg"
    description = "Embedded developer by Day, Gamer by Night."
#    tags = []

    headerEnableEmail = false
    headerEnableFollowme = true    

## Contents - Edit file /layouts/partials/home.html

    showSection1 = true
    showSection2 = true
    showSection3 = false
    showSection4 = false
    showSection5 = false
    showSection6 = false
    showSection7 = false
    showSection8 = false
    showSection9 = false
    
# Footers
    displayFooter = false    
    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    year = "2018"

# Content
## Menus
[[menu.main]]
    name = "home"
    url = "/"
    weight = 0
[[menu.main]]
    name = "blog"
    url = "post/"
    weight = 5
[[menu.main]]
    name = "about"
    url = "about/"
    weight = 10

## Footers
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/endywindaflame"
    icon = "fa-twitter-square"
    footer = true
    sharethis = false
    network = "twitter"

[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/cédric-saint-ghislain-76a08a110"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = false
    network = "linkedin"

[[params.social]]
    title = "github"
    url = "https://github.com/windaflame"
    icon = "fa-github"
    footer = true
    sharethis = true
    network = "github"

[[params.social]]
    title = "email"
    url = "mailto:dev.windaflame@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"