baseURL = "/"
languageCode = "en-us"
title = "Blog"
theme = "initio"
publishDir = "public"

[params]
    favicon = "images/guy.jpg"
    DateForm = "January 2, 2006"
    email = "dev.windaflame@gmail.com"

    name = "Endy WindAflame"
    avatar = "guy.jpg"
    description = "Embedded developer by Day, Gamer by Night."

    headerEnableEmail = false
    headerEnableFollowme = true    

    showSection1 = true
    showSection2 = true
    showSection3 = false
    showSection4 = false
    showSection5 = false
    showSection6 = false
    showSection7 = false
    showSection8 = false
    showSection9 = false
    
    displayFooter = false    
    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    year = "2018"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5    
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 10

[params.google.analytics]
    trackerID = "UA-115903272-1"

[[params.social]]
    title = "youtube"
    url = "https://www.youtube.com/channel/UCsbreMLpZK1iiX3Eea2O__g"
    icon = "fa-youtube-play"
    footer = true
    sharethis = true
    network = "youtube"
[[params.social]]
    title = "twitch"
    url = "https://www.twitch.tv/endy_windaflame"
    icon = "fa-twitch"
    footer = true
    sharethis = true
    network = "twitch"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/endywindaflame"
    icon = "fa-twitter-square"
    footer = true
    sharethis = false
    network = "twitter"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/cédric-saint-ghislain-76a08a110"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/windaflame"
    icon = "fa-github"
    footer = true
    sharethis = true
    network = "github"
[[params.social]]
    title = "email"
    url = "mailto:dev.windaflame@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"