baseURL = "/"
languageCode = "en-us"
title = "Blog"
theme = "hugo-initio"
publishDir = "public"

[params]
    avatar = "guy.jpg"
    name = "Endy WindAflame"
    description = "Embedded developer by Day, Gamer by Night."
    email = "dev.windaflame@gmail.com"
    phone = "+234 23 9873237"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2018
    background = ""
    favicon = "images/guy.jpg"
    DateForm = "January 2, 2006"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5    
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 10

[params.section.header]
    enableEmail = false
    enableFollowme = true

[params.section.subheader]
    show = true
    text = "All my projects are referenced below."

[params.section.service]
    show = false
    title = "Services"

[params.section.recentworks]
    show = true
    # Choose type "image", "summary" or "content"
    # For type image and summary. The content is loaded from data/recentworks.json.
    # For type content. The content is loaded by article from content/recentworks/*.md.
    type = "content"
    title = "Projects"

[params.section.download]
    show = false

[params.section.clients]
    show = false
    title = "Clients"

[params.section.upperfooter]
    show = false
    enableContact = true
    enableFollowme = true
    enableTextWidget = true
    enableFormWidget = true

[params.google.analytics]
    trackerID = "UA-115903272-1"

[[params.social]]
    title = "youtube"
    url = "https://www.youtube.com/channel/UCsbreMLpZK1iiX3Eea2O__g"
    icon = "fa-youtube-play"
    header = true
    footer = true
    sharethis = true
    network = "youtube"
[[params.social]]
    title = "twitch"
    url = "https://www.twitch.tv/endy_windaflame"
    icon = "fa-twitch"
    header = true
    footer = true
    sharethis = true
    network = "twitch"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/endywindaflame"
    icon = "fa-twitter-square"
    header = true
    footer = true
    sharethis = false
    network = "twitter"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/cédric-saint-ghislain-76a08a110"
    icon = "fa-linkedin-square"
    header = true
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/windaflame"
    icon = "fa-github"
    header = true
    footer = true
    sharethis = true
    network = "github"
[[params.social]]
    title = "email"
    url = "mailto:dev.windaflame@gmail.com"
    icon = "fa-envelope"
    header = true
    footer = true
    sharethis = true
    network = "email"