baseurl = "http://ewa-blog.netlify.com/"
languageCode = "en-uk"
title = "Blog - Endy WindAflame"
theme = "hugo-initio"

[params]
# Headers
    favicon = ""

#    customsharethis = ""

    name = "Endy WindAflame"
    description = "Embedded developer by Day, Gamer by Night."
#    email = "dev.windaflame@gmail.com"
    avatar ="guy.jpg"
#    tags = []

    DateForm = "January 2, 2006"
    headerEnableFollowme = true

## Contents
    showSubheader = true
    showProjects = true
    showRecentWorks = false
    showDownloads = false
    showClients = false
    
# Footers
    displayFooter = false
    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    year = "2018"

# Content
## Menus
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 2

## Footers
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/endywindaflame"
    icon = "fa-twitter-square"
    footer = true
    sharethis = false
    network = "twitter"

[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/cédric-saint-ghislain-76a08a110"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = false
    network = "linkedin"

[[params.social]]
    title = "github"
    url = "https://github.com/windaflame"
    icon = "fa-github"
    footer = true
    sharethis = true
    network = "github"

[[params.social]]
    title = "email"
    url = "mailto:dev.windaflame@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"