[build]
publish = "sources/zola-linkita/public"
command = "bash scripts/ci/production.sh"

[build.environment]
ZOLA_VERSION = "0.22.1"

[context.production]
command = "bash scripts/ci/production.sh"

[context.develop]
command = "bash scripts/ci/develop.sh"

[context.deploy-preview]
command = "bash scripts/ci/preview.sh"