[build]
publish = "public"
command = "bash scripts/ci/production.sh"

[build.environment]
ZOLA_VERSION = "0.20.0"

[context.deploy-preview]
command = "bash scripts/ci/preview.sh"

[dev]
command = "bash scripts/ci/develop.sh"